decoration {
    rounding = $ROUNDING
    rounding_power = 2
    active_opacity = $ACTIVE_OPACITY
    inactive_opacity = $INACTIVE_OPACITY

    shadow {
        enabled = false
    }

    blur {
        enabled = true
        size = $BLUR_SIZE
        passes = 3
        ignore_opacity = true
        xray = false
        new_optimizations = true

        vibrancy = 0.1696
    }
}
