general {
    gaps_in = 2
    gaps_out = 8
    border_size = 2
    col.active_border = $primary
    col.inactive_border = $background
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}
