general {
    gaps_in = $GAPS_IN
    gaps_out = $GAPS_OUT
    border_size = $BORDER_SIZE
    # col.active_border = $ACTIVE_BORDER_COLOR
    # col.inactive_border = $INACTIVE_BORDER_COLOR
    resize_on_border = false
    allow_tearing = false
    layout = scrolling
}
