source = ~/.config/hypr/variables.conf
source = ~/.config/hypr/window_rules.conf
source = ~/.config/hypr/layer_rules.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/autostart.conf

monitor=,$MONITOR_RESOLUTION,auto,$MONITOR_SCALE

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 1
    disable_hyprland_logo = true
    enable_swallow = true
    swallow_regex = ^(kitty)$
}


input {
    kb_layout = us,tr
    kb_variant =
    kb_model =
    kb_options = grp:win_space_toggle
    kb_rules =

    follow_mouse = true

    sensitivity = $MOUSE_SENSIVITY

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

xwayland {
  force_zero_scaling = true
}
