source = ./colors.conf
source = ./monitors.conf
source = ./variables.conf
source = ./environment-variables.conf
source = ./permissions.conf
source = ./general.conf
source = ./decoration.conf
source = ./animations.conf
source = ./workspace-rules.conf
source = ./input.conf
source = ./keybindings.conf
source = ./window-rules.conf
source = ./auto-start.conf


dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    force_default_wallpaper = 1
    disable_hyprland_logo = true
}
