layerrule {
    name = vicinae-blur
    match:namespace = vicinae
    blur = true
    ignore_alpha = 0
}

layerrule {
    name = vicinae-no-animation
    match:namespace = vicinae
    no_anim = true
}

layerrule {
    name = waybar-blur
    match:namespace = ^(dms:bar)$
    blur = true
}
