layerrule {
    name = vicinae-blur
    blur = true
    ignore_alpha = 0
    match:namespace = vicinae
}

layerrule {
    name = vicinae-no-animation
    no_anim = true
    match:namespace = vicinae
}
