# Root
$MAIN_MOD= SUPER

# Monitor variables
$MONITOR_RESOLUTION = 1920x1080@144
$MONITOR_SCALE = 1

# APPS
$TERMINAL = kitty
$FILE_MANAGER = dolphin
$MENU = hyprlauncher

# Design
$GAPS_IN = 4
$GAPS_OUT = 10

$ACTIVE_BORDER_COLOR = rgba(33CCFFEE) rgba(00FF99EE) 45deg
$INACTIVE_BORDER_COLOR = rgba(595959AA)
$BORDER_SIZE = 2

$ROUNDING = 0
$ACTIVE_OPACITY = 1.0
$INACTIVE_OPACITY = 1.0

$BLUR_SIZE = 3

# Cursor
$CURSOR_SIZE = 24
$MOUSE_SENSIVITY = 0
